name: 🧩 Module Federation
description: Tasks related to setup or updates of Webpack Module Federation between frontend apps.
labels: [ModuleFederation]
title: "[Module Federation] "
projects: ["DesiLinkr/7"]
body:
  - type: textarea
    attributes:
      label: What needs to be changed or added?
      description: Be specific — which apps are affected (host/remote), what modules are exposed/consumed, etc.
  - type: dropdown
    id: service
    attributes:
      label: Service/App
      options:
        - auth_service
        - access_core
        - url_service
        - url_app
        - shell_app
        - qrcode_service
        - qrcode_app
        - analytics_service
        - analytics_app
        - email_notification_service
        - background_jobs_service
        - adminpanel_app
        - settings_app
        - load_balancer
        - auth_app

  - type: textarea
    attributes:
      label: Additional Context
      description: Any links to PRs, diagrams, or error messages
